### ISSUE TITLE
yarn run generate also failed to open "cache/html-docs.json"

### ISSUE THREAD

**Issue by shroo-paulli** [cspotcode/cloudformation-declarations#4] opened 2018-02-20 23:44 UTC
$ pwsh -NoProfile -ExecutionPolicy RemoteSigned -File ./scripts/npm-run.ps1
{ Error: ENOENT: no such file or directory, open 'cache/html-docs.json'
    at Object.fs.openSync (fs.js:646:18)
    at Object.fs.readFileSync (fs.js:551:33)
    at readFile (/Users/pongli/my/git/CreditServiceApp/CustomModules/cloudformation-typescript-declarations/src/generator/utils.ts:90:15)
    at Object.readJsonFile (/Users/pongli/my/git/CreditServiceApp/CustomModules/cloudformation-typescript-declarations/src/generator/utils.ts:94:23)
    at /Users/pongli/my/git/CreditServiceApp/CustomModules/cloudformation-typescript-declarations/src/generator/index.ts:39:25
    at Generator.next (<anonymous>)
    at /Users/pongli/my/git/CreditServiceApp/CustomModules/cloudformation-typescript-declarations/node_modules/tslib/tslib.js:107:75
    at new Promise (<anonymous>)
    at Object.__awaiter (/Users/pongli/my/git/CreditServiceApp/CustomModules/cloudformation-typescript-declarations/node_modules/tslib/tslib.js:103:16)
    at main (/Users/pongli/my/git/CreditServiceApp/CustomModules/cloudformation-typescript-declarations/src/generator/index.ts:17:20)
    at Object.<anonymous> (/Users/pongli/my/git/CreditServiceApp/CustomModules/cloudformation-typescript-declarations/src/generator/index.ts:273:1)
    at Module._compile (module.js:635:30)
    at Module.m._compile (/Users/pongli/my/git/CreditServiceApp/CustomModules/cloudformation-typescript-declarations/node_modules/ts-node/src/index.ts:392:23)
    at Module._extensions..js (module.js:646:10)
    at Object.require.extensions.(anonymous function) [as .ts] (/Users/pongli/my/git/CreditServiceApp/CustomModules/cloudformation-typescript-declarations/node_modules/ts-node/src/index.ts:395:12)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Function.Module.runMain (module.js:676:10)
    at Object.<anonymous> (/Users/pongli/my/git/CreditServiceApp/CustomModules/cloudformation-typescript-declarations/node_modules/ts-node/src/_bin.ts:182:12)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: 'cache/html-docs.json' }
✨  Done in 2.84s.

**Comment by cspotcode** [comment] 2018-02-20 23:53
Duplicate of #3; same code path.

**Closed** 2018-02-20 23:54 UTC
